global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using FluentValidation;
global using Ardalis.Result;
global using TC.Agro.Analytics.Application.Configuration;
global using TC.Agro.Analytics.Domain.Aggregates;
global using TC.Agro.Analytics.Domain.ValueObjects;
global using TC.Agro.SharedKernel.Domain;
global using TC.Agro.SharedKernel.Infrastructure.Caching.Service;
global using Wolverine;
global using TC.Agro.SharedKernel.Application.Commands;
global using FastEndpoints;
global using TC.Agro.Analytics.Application.Abstractions.Mappers;
global using static TC.Agro.Analytics.Domain.Aggregates.AlertAggregate;
global using CacheTagCatalog = TC.Agro.Analytics.Application.Abstractions.CacheTags;
global using TC.Agro.Contracts.Events.SensorIngested;
